Updates pre_start_php action hook

diff --git a/.openshift/action_hooks/pre_start_php b/.openshift/action_hooks/pre_start_php
--- a/.openshift/action_hooks/pre_start_php
+++ b/.openshift/action_hooks/pre_start_php
@@ -13,25 +13,54 @@
 # Application start and stop is subject to different timeouts
 # throughout the system.
 
-# If there is no support for user-defined environment variables
-# set the DB_DRIVER using export.
-#
-if ! [ "$(type -t set_env_var)" == "function" ]; then
-  export APP_ENV="${APPLICATION_ENV:-production}"
+source $OPENSHIFT_CARTRIDGE_SDK_BASH
 
-  if [ ! -z "$OPENSHIFT_APP_DNS" ]; then
-    export APP_URL="$OPENSHIFT_APP_DNS"
+set -e
+
+echo 1>&2
+echo "Setting environment variables..." 1>&2
+
+export APP_ENV="${APPLICATION_ENV:-production}"
+if [ "$(type -t set_env_var)" == "function" ]; then
+  set_env_var 'APP_ENV' $APP_ENV $OPENSHIFT_HOMEDIR/.env/user_vars  
+fi
+
+if [ ! -z "$OPENSHIFT_APP_DNS" ]; then
+  export APP_URL="$OPENSHIFT_APP_DNS"
+  if [ "$(type -t set_env_var)" == "function" ]; then
+    set_env_var 'APP_URL' $APP_URL $OPENSHIFT_HOMEDIR/.env/user_vars
   fi
+fi
 
-  if [ ! -z "$OPENSHIFT_SECRET_TOKEN" ]; then
-    export APP_KEY=${OPENSHIFT_SECRET_TOKEN:0:31}
+if [ ! -z "$OPENSHIFT_SECRET_TOKEN" ]; then
+  export APP_KEY=${OPENSHIFT_SECRET_TOKEN:0:31}
+  if [ "$(type -t set_env_var)" == "function" ]; then
+    set_env_var 'APP_KEY' $APP_KEY $OPENSHIFT_HOMEDIR/.env/user_vars
   fi
+fi
 
-  if [ ! -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]; then
-    export DB_DRIVER="pgsql"
-  fi
+if [ ! -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]; then
+  export DB_DRIVER="pgsql"
+fi
 
-  if [ ! -z "$OPENSHIFT_MYSQL_DB_HOST" ]; then
-    export DB_DRIVER="mysql"
+if [ ! -z "$OPENSHIFT_MYSQL_DB_HOST" ]; then
+  export DB_DRIVER="mysql"
+fi
+
+if [ -z "$DB_DRIVER" ]; then
+  echo 1>&2
+  echo "Could not find the database cartridge.  Please run:" 1>&2
+  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.5" 1>&2
+  echo "or"
+  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-9.2" 1>&2
+  echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+  echo 1>&2
+  exit 5
+else
+  echo 1>&2
+  echo "Database driver set to '$DB_DRIVER'..." 1>&2
+  echo 1>&2
+  if [ "$(type -t set_env_var)" == "function" ]; then
+    set_env_var 'DB_DRIVER' $DB_DRIVER $OPENSHIFT_HOMEDIR/.env/user_vars
   fi
 fi
